
#module_parameters (DEBUG_BUILD := false, ASSERT_FAILURE_FUNC : (message: string) -> bool = null);

#import "Basic";
#import "Math";
#import "Random";
#import "Sloppy_Math";
Debug :: #import "Debug";

#load "gy_constants.jai";
#load "gy_polymorphism.jai";
#load "gy_intrinsics.jai";
#load "gy_vectors.jai";
#load "gy_colors.jai";
#load "gy_quaternions.jai";
#load "gy_rectangles.jai";
#load "gy_directions.jai";
#load "gy_assert.jai";
#load "gy_random.jai";
#load "gy_math.jai";
